Camera-Effects:
  spectator-mode: false
  invisible: true
  cinematic-mode: true
  hide-other-players: true
  hide-player: true

Point-Preview-Time: 5
On-Join:
  show-once: true
  random-player-camera-path: []

Messages:
  Commands:
    AddCommand:
      add: "&8(&6!&8) &fCommand added to camera!"
      help: "&8(&2!&8) &fUsage: &2/dc addcommand <command>"
      no-premission: "&8(&4!&8) &fYou don't have permission to use this command!"
    Select:
      select: "&8(&6!&8) &fCamera selected!"
      not-select: "&8(&c!&8) &fCamera not selected!"
      help: "&8(&2!&8) &fSelect a camera by doing &2/dc select <name>&f!"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
    AddPoint:
      add: "&8(&6!&8) &fPoint added to camera!"
      help: "&8(&2!&8) &fUsage: &2/dc addpoint [linear/teleport]"
      no-premission: "&8(&4!&8) &fYou don't have permission to use this command!"
    Create:
      created: "&8(&6!&8) &fCamera created!"
      already-exists: "&8(&c!&8) &fA camera already exists!"
      help: "&8(&2!&8) &fUsage: &2/dc create <name>"
      no-premission: "&8(&4!&8) &fYou don't have permission to use this command!"
    Help:
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
    Invisible:
      Help: "&8(&2!&8) &fUsage: &2/dc invisible <true/false>"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
    Remove:
      removed: "&8(&6!&8) &fCamera deleted!"
      not-found: "&8(&c!&8) &fA camera does not exists!"
      help: "&8(&2!&8) &fUsage: &2/dc remove <name>"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
    RemovePoint:
      success: "&8(&6!&8) Point removed from camera!"
      no-camera: "&8(&c!&8) &fNo camera selected!"
      help: "&8(&2!&8) &fUsage: &2/dc removepoint <name>"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
    SetDuration:
        success: "&8(&6!&8) Camera path duration set!"
        help: "&8(&2!&8) &fUsage: &2/dc setduration <duration>"
        no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
    Start:
      not-found: "&8(&c!&8) Camera not found!"
      already-started: "&8(&c!&8) Camera already active!"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
      help: "&8(&2!&8) &fUsage: &2/dc start <name>"
    StartOther:
      started: "&8(&6!&8) Camera started!"
      arleady-started: "&8(&c!&8) Camera already active!"
      player-not-found: "&8(&c!&8) Player not found!"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"
      help: "&8(&2!&8) &fUsage: &2/dc startother <player_name> <camera_name>"
    Stop:
      stopped: "&8(&6!&8) Camera stopped!"
      not-started: "&8(&c!&8) Camera not active!"
      no-permission: "&8(&4!&8) &fYou don't have permission to use this command!"