Camera-Effects:
  spectator-mode: true
  invisible: false

Point-Preview-Time: 5

Messages:
  Camera:
    viewing-stop: "Viewing stop"
    viewing-start: "Viewing start"
    viewing-preview-error: "Viewing preview error"
    viewing-preview-start: "Viewing preview start"
    viewing-preview-ended: "Viewing preview ended"
  Commands:
    AddCommand:
      add: "Add"
      help: "Help"
      no-premission: "No premission"
    Select:
      select: "Selected!"
      not-select: "Not selected"
      help: "Help"
      no-permission: "No premission"
    AddPoint:
      add: "Add"
      help: "Help"
      no-premission: "No premission"
    Create:
      created: "Created"
      already-exists: "Already exists"
      help: "Help"
      no-premission: "No premission"
    Help:
      no-permission: "No premission"
    Invisible:
      Help: "Help"
      no-permission: "No premission"
    Preview:
      no-camera: "No camera"
      arleady-active: "Already active"
      no-permission: "No premission"
    Remove:
      removed: "Removed"
      not-found: "Not found"
      help: "Help"
      no-permission: "No premission"
    RemovePoint:
      success: "Removed"
      no-camera: "No camera"
      help: "Help"
      no-permission: "No premission"
    SetDuration:
        success: "Set duration"
        help: "Help"
        no-permission: "No premission"
    Start:
      not-found: "Not found"
      already-started: "Already started"
      no-permission: "No premission"
      help: "Help"
    StartOther:
      started: "Started"
      arleady-started: "Already started"
      player-not-found: "Player not found"
      no-permission: "No premission"
      help: "Help"
    Stop:
      stopped: "Stopped"
      not-started: "Not started"
      no-permission: "No premission"